import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-3xl mx-auto">
           <header className="bg-black text-white flex justify-between p-6 rounded-lg">
<Link href={"/"} className="font-bold text-2xl">Admin Dashboard</Link>
<Link href={"/create"} className="bg-amber-200 grid place-items-center  text-black rounded-full shadow-md px-3 py-2">Add Menu</Link>
        </header>
        </div>
       
        <main>
           {children}
        </main>
       
      </body>
    </html>
  );
}
